"""empty message

Revision ID: 151e845b202
Revises: 3d35bbfb09a
Create Date: 2015-10-18 02:54:38.539321

"""

# revision identifiers, used by Alembic.
revision = '151e845b202'
down_revision = '3d35bbfb09a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
