"""empty message

Revision ID: 3b3a678e624
Revises: 161ab9d3cb9
Create Date: 2015-10-03 10:32:44.093615

"""

# revision identifiers, used by Alembic.
revision = '3b3a678e624'
down_revision = '161ab9d3cb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
